### ISSUE TITLE
[feat] Context API 적용

### ISSUE THREAD

**Issue by 2kyung19** [wanted-pre-onboading-10/sirloin-admin-page#13]
# TASK CARD

**Task Description**
1. Context API 적용
2. alert function

**Date :** 22.01.29 ~ 

## to-do

- [x] Context API
- [ ] alert

**Comment by Jeontaeyun** [comment]
### Comment

Context API안에 `useMemo`가 있는 것을 발견했는데, `useMemo`는 컨텍스트 내부의 상태를 변경하는 `setState`에 의해 컨텍스트 내부 코드가 재 실행될 때, `[]` 의존성 내부의 데이터가 변경되면 `useMemo`내부의 계산을 재 실행하는 기능을 제공합니다.

즉, 현재의 구조와 같이 `context`내부의 데이터를 바꿀 때마다 반드시 `useMemo`가 재 실행되는 경우에는 `useMemo`를 쓰지 않는 것이 리소스 사용 측면에서는 더 유용합니다.

**Comment by 2kyung19** [comment]
@Jeontaeyun comment 감사합니다!

Context API를 적용하다가, `Provider` `value`에 들어가는 데이터를 `useMemo` 없이 정의해보니

`The 'ProductInfo' object (at line 14) passed as the value prop to the Context provider (at line 28) changes every render. To fix this consider wrapping it in a useMemo hook.`

라는 에러를 마주하게 되어 메시지에 따라 `useMemo`를 적용시켰습니다. 

말씀하신 데로 `useMemo`가 의미 없는 구조에서, 현재 에러 상황에는 `'eslint react/jsx-no-constructed-context-values'` 를 비활성화시키는 방법을 고려해보는 것도 좋을 것 같습니다!

조금 더 학습한 후 개선해보겠습니다 :)
